version: "3.7"

services:
  analang-router:
    image: traefik/whoami:latest
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true

        # HTTP
        - traefik.http.routers.analang-http.rule=Host(`analang.fazinzz.com`)
        - traefik.http.routers.analang-http.entrypoints=web
        - traefik.http.routers.analang-http.service=analang-backend

        # HTTPS
        - traefik.http.routers.analang.rule=Host(`analang.fazinzz.com`)
        - traefik.http.routers.analang.entrypoints=websecure
        - traefik.http.routers.analang.tls.certresolver=letsencryptresolver
        - traefik.http.routers.analang.service=analang-backend

        # Backend (porta 3202 - ana-langgraph)
        - traefik.http.services.analang-backend.loadbalancer.server.url=http://172.17.0.1:3202

networks:
  network_public:
    external: true
    name: network_public
